[build]
base = "/"
command = "npm run build"
publish = "dist/public"

[build.environment]
NODE_VERSION = "18"

[[redirects]]
from = "/api/*"
to = "https://google-sheet-search-portal-api.onrender.com/api/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200